name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk unzip git zip \
            python3-pip libffi-dev libssl-dev python3-distutils \
            libjpeg-dev libxcursor-dev libxrandr-dev libxinerama-dev \
            libxi-dev libgl1-mesa-dev libgles2-mesa-dev xclip xsel

      - name: Set ANDROID_HOME to GitHub SDK
        run: |
          echo "ANDROIDSDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROIDNDK=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install Buildozer
        run: pip install --user buildozer cython==0.29.36

      - name: Build APK
        run: buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShopTracker-debug-apk
          path: bin/*.apk
